In [2]:
import pandas as pd
import json
from sklearn import preprocessing
import numpy as np
import matplotlib.pyplot as plt

# 1. Data exploration
deep dive into the world of pandas

## 1.1 UntypedDataSet

In [3]:
# initialiseer dataframe.
dfUntypedDataSet = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/UntypedDataSet?$top=1")

In [4]:
# Loop tot alle data points in dataframe zitten met limiet van 10000 per keer.
top = 9668
skip = 1
while skip < 96681:
    big = dfUntypedDataSet.append(pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/UntypedDataSet?$top=" + str(top) + "&$skip=" + str(skip)))
    skip = skip + 9668
    dfUntypedDataSet = big

Nu hebben we de alle UntypedDataSet in een df, hiervan willen we alleen de values.

In [5]:
# lijst maken van values in df.
DatasetUntypesList = dfUntypedDataSet["value"].tolist()

In [6]:
# dataframe maken van lijst met beoogde values.
newDF = pd.DataFrame(DatasetUntypesList)

In [7]:
newDF

,Afzet,BedrijfstakkenBranchesSBI2008,ID,OntwikkelingTOV1JaarEerder_2,OntwikkelingTOV1MaandEerder_3,Perioden,ProducentenprijsindexPPI_1,Wegingcoefficient_4
0,A6,305700,0,,,1981MM01,53.8,-
1,A6,305700,1,,0.6,1981MM02,54.1,-
2,A6,305700,2,,0.4,1981MM03,54.3,-
3,A6,305700,3,,0.0,1981MM04,54.3,-
4,A6,305700,4,,0.4,1981MM05,54.5,-
5,A6,305700,5,,1.0,1981MM06,55.0,-
6,A6,305700,6,,1.0,1981MM07,55.6,-
7,A6,305700,7,,-0.1,1981MM08,55.5,-
8,A6,305700,8,,-0.2,1981MM09,55.4,-
9,A6,305700,9,,-0.1,1981MM10,55.4,-
10,A6,305700,10,,0.0,1981MM11,55.4,-
11,A6,305700,11,,0.0,1981MM12,55.4,-
12,A6,305700,12,,,1981JJ00,54.9,-
13,A6,305700,13,7.6,4.5,1982MM01,57.9,-
14,A6,305700,14,7.8,0.8,1982MM02,58.3,-
15,A6,305700,15,8.1,0.7,1982MM03,58.7,-
16,A6,305700,16,9.4,1.2,1982MM04,59.4,-
17,A6,305700,17,9.4,0.3,1982MM05,59.6,-
18,A6,305700,18,8.0,-0.3,1982MM06,59.4,-
19,A6,305700,19,6.5,-0.3,1982MM07,59.2,-
20,A6,305700,20,6.2,-0.4,1982MM08,58.9,-
21,A6,305700,21,5.7,-0.6,1982MM09,58.6,-
22,A6,305700,22,5.7,0.0,1982MM10,58.5,-
23,A6,305700,23,6.6,0.8,1982MM11,59.0,-
24,A6,305700,24,6.7,0.2,1982MM12,59.1,-
25,A6,305700,25,7.3,,1982JJ00,58.9,-
26,A6,305700,26,2.5,0.3,1983MM01,59.3,-
27,A6,305700,27,1.7,-0.1,1983MM02,59.3,-
28,A6,305700,28,0.9,0.0,1983MM03,59.2,-
29,A6,305700,29,-0.3,0.0,1983MM04,59.2,-
...,...,...,...,...,...,...,...,...
96651,A5,348100,96651,,,2015MM10,,-
96652,A5,348100,96652,,,2015MM11,,-
96653,A5,348100,96653,,,2015MM12,,-
96654,A5,348100,96654,,,2015JJ00,,-
96655,A5,348100,96655,,,2016MM01,,-
96656,A5,348100,96656,,,2016MM02,,-
96657,A5,348100,96657,,,2016MM03,,-
96658,A5,348100,96658,,,2016MM04,,-
96659,A5,348100,96659,,,2016MM05,,-
96660,A5,348100,96660,,,2016MM06,,-
96661,A5,348100,96661,,,2016MM07,,-
96662,A5,348100,96662,,,2016MM08,,-
96663,A5,348100,96663,,,2016MM09,,-
96664,A5,348100,96664,,,2016MM10,,-
96665,A5,348100,96665,,,2016MM11,,-
96666,A5,348100,96666,,,2016MM12,,-
96667,A5,348100,96667,,,2016JJ00,,-
96668,A5,348100,96668,,,2017MM01,,-
96669,A5,348100,96669,,,2017MM02,,-
96670,A5,348100,96670,,,2017MM03,,-
96671,A5,348100,96671,,,2017MM04,,-
96672,A5,348100,96672,,,2017MM05,,-
96673,A5,348100,96673,,,2017MM06,,-
96674,A5,348100,96674,,,2017MM07,,-
96675,A5,348100,96675,,,2017MM08,,-
96676,A5,348100,96676,,,2017MM09,,-
96677,A5,348100,96677,,,2017MM10,,-
96678,A5,348100,96678,,,2017MM11,,-
96679,A5,348100,96679,,,2017MM12,,-
96680,A5,348100,96680,,,2017JJ00,,-

## 1.2 Typed DataSet

In [8]:
dftypedDataSet = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/TypedDataSet?$top=1")

In [9]:
top = 9668
skip = 1
url = "http://opendata.cbs.nl/ODataApi/OData/81975NED/TypedDataSet"
while skip < 96681:
    big = dftypedDataSet.append(pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/TypedDataSet?$top=" + str(top) + "&$skip=" + str(skip)))
    skip = skip + 9668
    dftypedDataSet = big

In [10]:
# lijst maken van values in df.
DatasetTypedList = dftypedDataSet["value"].tolist()

In [11]:
# dataframe maken van lijst met beoogde values.
newDF2 = pd.DataFrame(DatasetTypedList)

In [12]:
columns = newDF2.columns
columns

Index([u'Afzet', u'BedrijfstakkenBranchesSBI2008', u'ID',
       u'OntwikkelingTOV1JaarEerder_2', u'OntwikkelingTOV1MaandEerder_3',
       u'Perioden', u'ProducentenprijsindexPPI_1', u'Wegingcoefficient_4'],
      dtype='object')

In [13]:
newDF2.head()

,Afzet,BedrijfstakkenBranchesSBI2008,ID,OntwikkelingTOV1JaarEerder_2,OntwikkelingTOV1MaandEerder_3,Perioden,ProducentenprijsindexPPI_1,Wegingcoefficient_4
0,A6,305700,0,NaN,NaN,1981MM01,53.8,0.0
1,A6,305700,1,NaN,0.6,1981MM02,54.1,0.0
2,A6,305700,2,NaN,0.4,1981MM03,54.3,0.0
3,A6,305700,3,NaN,0.0,1981MM04,54.3,0.0
4,A6,305700,4,NaN,0.4,1981MM05,54.5,0.0

## 1.2.1 Inspecting Data

In [14]:
#Describe the sepal length column
#print("Mean:" + str(newDF2["Afzet"].mean()))
#print("Standard deviation: " + str(newDF2["Afzet"].std()))
#print("Kurtosis: " + str(newDF2["Afzet"].kurtosis()))
#print("Skewness: " + str(newDF2["Afzet"].skew()))

# All data laten zien dat ontbreekt.
newDF2.isnull().sum()

Afzet                                0
BedrijfstakkenBranchesSBI2008        0
ID                                   0
OntwikkelingTOV1JaarEerder_2     39885
OntwikkelingTOV1MaandEerder_3    41120
Perioden                             0
ProducentenprijsindexPPI_1       36179
Wegingcoefficient_4                  0
dtype: int64

In [15]:
# pandas dataframe met alleen columns waar data ontbreekt.
missingData = newDF2[["BedrijfstakkenBranchesSBI2008","OntwikkelingTOV1JaarEerder_2","OntwikkelingTOV1MaandEerder_3", "Perioden" ,"ProducentenprijsindexPPI_1"]]

# df met data waar alle data ontbreekt.
allMissing = missingData.loc[(missingData["OntwikkelingTOV1JaarEerder_2"].isnull()) & (missingData["OntwikkelingTOV1MaandEerder_3"].isnull()) & (missingData["ProducentenprijsindexPPI_1"].isnull())]

In [46]:
i = 0
branches936 = []
dates936 = []
smallBranches = []
bigBranches = []
tempBranch = []

# loop over alle branches, isoleer branch, verkrijg alle rows waarbij alle data ontbreekt.
# als er precies 936 data punten ontbreekt sla het op in list en de bijhorende datums.
while i < len(newDF2["BedrijfstakkenBranchesSBI2008"].unique()):
    branch = newDF2["BedrijfstakkenBranchesSBI2008"].unique()[i]
    foo = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == branch]
    x = len(foo)
    bar = foo.loc[(foo["OntwikkelingTOV1JaarEerder_2"].isnull()) & (foo["OntwikkelingTOV1MaandEerder_3"].isnull()) & (foo["ProducentenprijsindexPPI_1"].isnull())]
    tar = foo.loc[(foo["OntwikkelingTOV1JaarEerder_2"].isnull()) | (foo["OntwikkelingTOV1MaandEerder_3"].isnull()) | (foo["ProducentenprijsindexPPI_1"].isnull())]
    y = len(bar)
    z = len(tar)
    if y == 936:
        branches936.append(branchNamen.loc[branchNamen["Key"] == branch]["Title"].tolist())
        dates936.append(bar["Perioden"].tolist())
    elif y != 936 and y > 100:
        bigBranches.append(branch)
        #print(branch, x, y, z)
    elif y > 0 and y < 100:
        smallBranches.append(branch)
        #print(branch, x, y, z)
    elif z == 183:
        tempBranch.append(branch)
    print(branch, x, y, z) 
    i += 1

(u'.306300', 1443, 0, 183)
(u'.307500', 1443, 0, 183)
(u'.307600', 1443, 0, 183)
(u'308100', 1443, 940, 1017)
(u'310100', 1443, 1391, 1407)
(u'.311300', 1443, 0, 183)
(u'311600', 1443, 1443, 1443)
(u'.312500', 1443, 0, 183)
(u'.314000', 1443, 0, 183)
(u'.315800', 1443, 0, 183)
(u'.317100', 1443, 0, 183)
(u'.318600', 1443, 0, 183)
(u'.320700', 1443, 0, 183)
(u'.323200', 1443, 0, 183)
(u'.323700', 1443, 0, 183)
(u'.324600', 1443, 0, 183)
(u'.328100', 1443, 0, 183)
(u'.330300', 1443, 0, 183)
(u'.332900', 1443, 0, 183)
(u'.334800', 1443, 0, 183)
(u'.336500', 1443, 0, 183)
(u'.339200', 1443, 0, 183)
(u'.340200', 1443, 0, 183)
(u'.341600', 1443, 0, 183)
(u'.342400', 1443, 0, 183)
(u'344400', 1443, 1235, 1275)
(u'348000', 1443, 481, 603)
(u'348100', 1443, 481, 603)

In [18]:
tempBranch

[u'306300', u'307500']

In [19]:
for i in tempBranch:  
    print(branchNamen.loc[branchNamen["Key"] == i])

NameError: name 'branchNamen' is not defined

In [20]:
# de 183 missing data te wijten aan begin van meting en zgn jaar meting?
dummy = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == "311300"]
dummy

,Afzet,BedrijfstakkenBranchesSBI2008,ID,OntwikkelingTOV1JaarEerder_2,OntwikkelingTOV1MaandEerder_3,Perioden,ProducentenprijsindexPPI_1,Wegingcoefficient_4
12987,A6,311300,12987,NaN,NaN,1981MM01,52.8,0.0
12988,A6,311300,12988,NaN,0.1,1981MM02,52.8,0.0
12989,A6,311300,12989,NaN,1.2,1981MM03,53.5,0.0
12990,A6,311300,12990,NaN,-0.1,1981MM04,53.4,0.0
12991,A6,311300,12991,NaN,0.1,1981MM05,53.4,0.0
12992,A6,311300,12992,NaN,0.0,1981MM06,53.5,0.0
12993,A6,311300,12993,NaN,0.5,1981MM07,53.7,0.0
12994,A6,311300,12994,NaN,0.0,1981MM08,53.7,0.0
12995,A6,311300,12995,NaN,0.2,1981MM09,53.8,0.0
12996,A6,311300,12996,NaN,0.1,1981MM10,53.8,0.0
12997,A6,311300,12997,NaN,0.7,1981MM11,54.2,0.0
12998,A6,311300,12998,NaN,0.3,1981MM12,54.4,0.0
12999,A6,311300,12999,NaN,NaN,1981JJ00,53.6,0.0
13000,A6,311300,13000,11.2,7.9,1982MM01,58.7,0.0
13001,A6,311300,13001,11.2,0.1,1982MM02,58.8,0.0
13002,A6,311300,13002,10.1,0.1,1982MM03,58.8,0.0
13003,A6,311300,13003,10.3,0.2,1982MM04,58.9,0.0
13004,A6,311300,13004,10.3,0.0,1982MM05,58.9,0.0
13005,A6,311300,13005,10.3,0.0,1982MM06,58.9,0.0
13006,A6,311300,13006,10.3,0.5,1982MM07,59.2,0.0
13007,A6,311300,13007,10.3,0.0,1982MM08,59.2,0.0
13008,A6,311300,13008,10.1,0.0,1982MM09,59.2,0.0
13009,A6,311300,13009,10.0,0.0,1982MM10,59.2,0.0
13010,A6,311300,13010,10.0,0.7,1982MM11,59.6,0.0
13011,A6,311300,13011,10.0,0.3,1982MM12,59.8,0.0
13012,A6,311300,13012,10.3,NaN,1982JJ00,59.1,0.0
13013,A6,311300,13013,2.7,0.8,1983MM01,60.3,0.0
13014,A6,311300,13014,2.7,0.1,1983MM02,60.3,0.0
13015,A6,311300,13015,2.6,0.0,1983MM03,60.3,0.0
13016,A6,311300,13016,2.4,0.1,1983MM04,60.4,0.0
...,...,...,...,...,...,...,...,...
77892,A5,311300,77892,-1.1,0.0,2015MM10,104.4,2216.0
77893,A5,311300,77893,-1.5,0.0,2015MM11,104.4,2216.0
77894,A5,311300,77894,-0.4,-0.5,2015MM12,103.9,2216.0
77895,A5,311300,77895,-0.7,NaN,2015JJ00,105.0,2216.0
77896,A5,311300,77896,2.6,1.7,2016MM01,105.7,2216.0
77897,A5,311300,77897,1.6,-0.3,2016MM02,105.4,2216.0
77898,A5,311300,77898,1.1,0.2,2016MM03,105.7,2216.0
77899,A5,311300,77899,0.1,0.6,2016MM04,106.3,2216.0
77900,A5,311300,77900,0.2,0.3,2016MM05,106.6,2216.0
77901,A5,311300,77901,0.2,0.3,2016MM06,107.0,2216.0
77902,A5,311300,77902,0.5,0.4,2016MM07,107.4,2216.0
77903,A5,311300,77903,2.0,0.2,2016MM08,107.6,2216.0
77904,A5,311300,77904,2.8,-0.2,2016MM09,107.4,2216.0
77905,A5,311300,77905,3.1,0.3,2016MM10,107.7,2216.0
77906,A5,311300,77906,3.5,0.3,2016MM11,108.0,2216.0
77907,A5,311300,77907,3.9,0.0,2016MM12,108.0,2216.0
77908,A5,311300,77908,1.8,NaN,2016JJ00,106.9,2216.0
77909,A5,311300,77909,3.2,1.1,2017MM01,109.2,2216.0
77910,A5,311300,77910,3.7,0.2,2017MM02,109.4,2216.0
77911,A5,311300,77911,3.4,-0.1,2017MM03,109.2,2216.0
77912,A5,311300,77912,1.8,-0.9,2017MM04,108.2,2216.0
77913,A5,311300,77913,1.3,-0.2,2017MM05,108.0,2216.0
77914,A5,311300,77914,0.6,-0.4,2017MM06,107.6,2216.0
77915,A5,311300,77915,0.9,0.6,2017MM07,108.3,2216.0
77916,A5,311300,77916,0.7,0.1,2017MM08,108.4,2216.0
77917,A5,311300,77917,1.0,0.1,2017MM09,108.5,2216.0
77918,A5,311300,77918,1.2,0.5,2017MM10,109.0,2216.0
77919,A5,311300,77919,1.2,0.3,2017MM11,109.4,2216.0
77920,A5,311300,77920,1.6,0.3,2017MM12,109.7,2216.0
77921,A5,311300,77921,1.7,NaN,2017JJ00,108.7,2216.0

## 1.2.2 dealing with missing data

##### Alle branches waar precies 936 data punten ontbreken.

In [21]:
branches936

[]

In [22]:
# Alle datums van de branches waar precies 936 miste komen overeen.
# Vanaf begin 1981 tot eind 2004 is er voor deze branches niks gemeten.
dates936

[]

#### Data waarbij prijs in alle gevallen ontbrak bij minder dan 100 data punten

In [23]:
for i in smallBranches:  
    print(branchNamen.loc[branchNamen["Key"] == i])

NameError: name 'branchNamen' is not defined

In [24]:
smallBranches

[u'305700', u'305800']

In [25]:
smallRemoved = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == "305700"]

for item in smallBranches:
    if item != "305700":
        temp = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == item]
        temp = temp.loc[(temp["OntwikkelingTOV1JaarEerder_2"].notnull()) | (temp["OntwikkelingTOV1MaandEerder_3"].notnull()) | (temp["ProducentenprijsindexPPI_1"].notnull())]
        smallRemoved = smallRemoved.append(temp)

#smallRemoved
testData = smallRemoved.interpolate()
testData.isnull().sum()

Afzet                             0
BedrijfstakkenBranchesSBI2008     0
ID                                0
OntwikkelingTOV1JaarEerder_2     13
OntwikkelingTOV1MaandEerder_3     1
Perioden                          0
ProducentenprijsindexPPI_1        0
Wegingcoefficient_4               0
dtype: int64

#### Data waarbij prijs in alle gevallen ontbrak bij meer dan 100 data punten

In [51]:
for i in bigBranches:  
    print(branchNamen.loc[branchNamen["Key"] == i])

       Key                         Title
10  308100  102 Visverwerkende industrie
       Key                 Title
24  310100  1081 Suikerindustrie
       Key                             Title
28  311600  1102 Wijnindustrie (uit druiven)
       Key                                     Title
62  344400  33 Reparatie en installatie van machines
       Key                            Title
65  348000  E Waterbedrijven en afvalbeheer
       Key                     Title
66  348100  36 Waterleidingbedrijven

In [84]:
jaarlozenummers = []
for i,datum in enumerate(newDF2["Perioden"].tolist()):
    if datum.find("MM") != -1:
        jaarlozenummers.append(i)

CleanDF2 = newDF2.iloc[jaarlozenummers]
CleanDF2 = CleanDF2.drop(columns=["Wegingcoefficient_4"])

In [85]:
afzet = ["A4","A5","A6"]
for i in branchNamen["Key"]:
    BranchTemp = CleanDF2.loc[CleanDF2["BedrijfstakkenBranchesSBI2008"] == i]
    BranchTemp = BranchTemp.interpolate()
    BranchClean = BranchTemp.loc[(BranchTemp["OntwikkelingTOV1JaarEerder_2"].notnull()) | (BranchTemp["OntwikkelingTOV1MaandEerder_3"].notnull()) | (BranchTemp["ProducentenprijsindexPPI_1"].notnull())]
    for k in afzet:
        BranchCleanAfzet = BranchClean.loc[BranchClean["Afzet"] == k]
        BranchCleanAfzet.to_csv(i + " - " + k)

In [48]:
# 308100 begint later (Visverwerkende industrie)
#temp1 = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == "308100"]
#temp1.loc[(temp1["OntwikkelingTOV1JaarEerder_2"].notnull()) | (temp1["OntwikkelingTOV1MaandEerder_3"].notnull()) | (temp1["ProducentenprijsindexPPI_1"].notnull())]

,Afzet,BedrijfstakkenBranchesSBI2008,ID,OntwikkelingTOV1JaarEerder_2,OntwikkelingTOV1MaandEerder_3,Perioden,ProducentenprijsindexPPI_1,Wegingcoefficient_4
5122,A6,308100,5122,NaN,NaN,2005MM01,92.3,607.0
5123,A6,308100,5123,NaN,1.8,2005MM02,94.0,607.0
5124,A6,308100,5124,NaN,-1.1,2005MM03,93.0,607.0
5125,A6,308100,5125,NaN,-1.6,2005MM04,91.5,607.0
5126,A6,308100,5126,NaN,0.2,2005MM05,91.7,607.0
5127,A6,308100,5127,NaN,3.3,2005MM06,94.7,607.0
5128,A6,308100,5128,NaN,-0.7,2005MM07,94.1,607.0
5129,A6,308100,5129,NaN,1.3,2005MM08,95.3,607.0
5130,A6,308100,5130,NaN,-1.5,2005MM09,93.8,607.0
5131,A6,308100,5131,NaN,2.4,2005MM10,96.1,607.0
5132,A6,308100,5132,NaN,1.4,2005MM11,97.4,607.0
5133,A6,308100,5133,NaN,-2.0,2005MM12,95.5,607.0
5134,A6,308100,5134,NaN,NaN,2005JJ00,94.1,607.0
5135,A6,308100,5135,2.5,-0.9,2006MM01,94.6,607.0
5136,A6,308100,5136,1.3,0.7,2006MM02,95.3,607.0
5137,A6,308100,5137,5.0,2.5,2006MM03,97.7,607.0
5138,A6,308100,5138,5.2,-1.4,2006MM04,96.3,607.0
5139,A6,308100,5139,3.1,-1.8,2006MM05,94.6,607.0
5140,A6,308100,5140,0.5,0.6,2006MM06,95.2,607.0
5141,A6,308100,5141,2.6,1.4,2006MM07,96.5,607.0
5142,A6,308100,5142,0.8,-0.4,2006MM08,96.1,607.0
5143,A6,308100,5143,3.9,1.5,2006MM09,97.5,607.0
5144,A6,308100,5144,0.9,-0.6,2006MM10,97.0,607.0
5145,A6,308100,5145,0.7,1.2,2006MM11,98.1,607.0
5146,A6,308100,5146,3.1,0.3,2006MM12,98.4,607.0
5147,A6,308100,5147,2.5,NaN,2006JJ00,96.4,607.0
5148,A6,308100,5148,4.3,0.2,2007MM01,98.7,607.0
5149,A6,308100,5149,5.1,1.5,2007MM02,100.1,607.0
5150,A6,308100,5150,2.9,0.4,2007MM03,100.5,607.0
5151,A6,308100,5151,3.2,-1.2,2007MM04,99.3,607.0
...,...,...,...,...,...,...,...,...
69715,A5,308100,69715,2.8,-0.3,2015MM10,108.2,533.0
69716,A5,308100,69716,4.2,1.5,2015MM11,109.8,533.0
69717,A5,308100,69717,2.9,0.4,2015MM12,110.3,533.0
69718,A5,308100,69718,2.6,NaN,2015JJ00,107.7,533.0
69719,A5,308100,69719,3.4,-0.4,2016MM01,109.8,533.0
69720,A5,308100,69720,4.7,0.6,2016MM02,110.4,533.0
69721,A5,308100,69721,2.7,-1.4,2016MM03,108.9,533.0
69722,A5,308100,69722,0.7,-0.4,2016MM04,108.4,533.0
69723,A5,308100,69723,1.7,0.9,2016MM05,109.4,533.0
69724,A5,308100,69724,0.2,-1.1,2016MM06,108.2,533.0
69725,A5,308100,69725,1.5,-0.1,2016MM07,108.1,533.0
69726,A5,308100,69726,2.4,2.5,2016MM08,110.8,533.0
69727,A5,308100,69727,2.5,0.4,2016MM09,111.2,533.0
69728,A5,308100,69728,4.1,1.2,2016MM10,112.6,533.0
69729,A5,308100,69729,2.4,-0.1,2016MM11,112.4,533.0
69730,A5,308100,69730,2.9,0.9,2016MM12,113.5,533.0
69731,A5,308100,69731,2.4,NaN,2016JJ00,110.3,533.0
69732,A5,308100,69732,4.6,1.2,2017MM01,114.8,533.0
69733,A5,308100,69733,4.6,0.6,2017MM02,115.4,533.0
69734,A5,308100,69734,5.8,-0.2,2017MM03,115.3,533.0
69735,A5,308100,69735,6.7,0.4,2017MM04,115.7,533.0
69736,A5,308100,69736,4.0,-1.7,2017MM05,113.8,533.0
69737,A5,308100,69737,3.5,-1.5,2017MM06,112.0,533.0
69738,A5,308100,69738,3.8,0.2,2017MM07,112.2,533.0
69739,A5,308100,69739,3.0,1.7,2017MM08,114.1,533.0
69740,A5,308100,69740,2.4,-0.1,2017MM09,114.0,533.0
69741,A5,308100,69741,1.0,-0.3,2017MM10,113.7,533.0
69742,A5,308100,69742,1.7,0.5,2017MM11,114.3,533.0
69743,A5,308100,69743,1.6,0.9,2017MM12,115.3,533.0
69744,A5,308100,69744,3.5,NaN,2017JJ00,114.2,533.0

In [29]:
#310100 van 2005 tot 2008 gemeten. (Suikerindustrie)
#temp1 = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == "310100"]
#temp1.loc[(temp1["OntwikkelingTOV1JaarEerder_2"].notnull()) | (temp1["OntwikkelingTOV1MaandEerder_3"].notnull()) | (temp1["ProducentenprijsindexPPI_1"].notnull())]

In [30]:
# 311600 helemaal leeg. (1102 Wijnindustrie uit druiven) Laten vallen.
#temp1 = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == "311600"]
#temp1.loc[(temp1["OntwikkelingTOV1JaarEerder_2"].notnull()) | (temp1["OntwikkelingTOV1MaandEerder_3"].notnull()) | (temp1["ProducentenprijsindexPPI_1"].notnull())]

In [31]:
# 344400 begint 2010 tot 2017. Reparatie en installatie van machines.
#temp1 = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == "344400"]
#temp1.loc[(temp1["OntwikkelingTOV1JaarEerder_2"].notnull()) | (temp1["OntwikkelingTOV1MaandEerder_3"].notnull()) | (temp1["ProducentenprijsindexPPI_1"].notnull())]

In [32]:
# Helemaal leeg. 348000  Waterbedrijven en afvalbeheer laten vallen.
#temp1 = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == "3348000"]
#temp1.loc[(temp1["OntwikkelingTOV1JaarEerder_2"].notnull()) | (temp1["OntwikkelingTOV1MaandEerder_3"].notnull()) | (temp1["ProducentenprijsindexPPI_1"].notnull())]

In [33]:
# Waterleidingbedrijven 348100 begint 1981 tot eind 2017. Is volledig, heeft maar 1 meting per maand.
#temp1 = newDF2.loc[newDF2["BedrijfstakkenBranchesSBI2008"] == "348100"]
#temp1.loc[(temp1["OntwikkelingTOV1JaarEerder_2"].notnull()) | (temp1["OntwikkelingTOV1MaandEerder_3"].notnull()) | (temp1["ProducentenprijsindexPPI_1"].notnull())]

### 1.3TableInfos

In [34]:
dfTableInfos = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/TableInfos")

In [35]:
dfTableInfos["value"]

0    {u'MetaDataModified': u'2018-03-19T02:00:00', ...
Name: value, dtype: object

### 1.4 DataProperties

In [36]:
dfDataProperties = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/DataProperties")
dfDataProperties["value"]

0    {u'odata.type': u'Cbs.OData.Dimension', u'Desc...
1    {u'odata.type': u'Cbs.OData.Dimension', u'Desc...
2    {u'ReleasePolicy': True, u'odata.type': u'Cbs....
3    {u'odata.type': u'Cbs.OData.Topic', u'Descript...
4    {u'odata.type': u'Cbs.OData.Topic', u'Descript...
5    {u'odata.type': u'Cbs.OData.Topic', u'Descript...
6    {u'odata.type': u'Cbs.OData.Topic', u'Descript...
Name: value, dtype: object

### 1.5 CategoryGroups

In [37]:
dfCategoryGroups = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/CategoryGroups")
listCat = dfCategoryGroups["value"].tolist()
pdCatGroup = pd.DataFrame(listCat)

### 1.6 Afzet

In [38]:
dfAfzet = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/Afzet")
dfAfzet["value"][0]

{u'CategoryGroupID': None,
 u'Description': u'Afzet van in Nederland geproduceerde goederen door de betreffende (sub)sectie(s) ongeacht of deze zijn afgezet in binnenland of buitenland. ',
 u'Key': u'A6',
 u'Title': u'Totaal'}

A6: Afzet van in Nederland geproduceerde goederen door de betreffende (sub)sectie(s) ongeacht of deze zijn afgezet in binnenland of buitenland. AKA Totaal.

A4: Binnenlandse afzet van in Nederland geproduceerde goederen door de betreffende bedrijfstakken. Binnenlandse afzet.

A5: Buitenlandse afzet van in Nederland geproduceerde goederen door de betreffende bedrijfstakken. AKA Buitenlands Afzet.

### 1.7 BedrijfstakkenBranchesSBI2008

In [39]:
dfBedrijfstakkenBranchesSBI2008 = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/BedrijfstakkenBranchesSBI2008")
listBedrijfstakken = dfBedrijfstakkenBranchesSBI2008["value"].tolist()
pdBedrijfstakkenSBI = pd.DataFrame(listBedrijfstakken)

In [42]:
#dfBedrijfstakkenBranchesSBI2008.loc[newDF2['Value'] == "A6"]
branchNamen = pdBedrijfstakkenSBI[["Key","Title"]]
branchNamen

       Key                                     Title
0   305700                      B Delfstoffenwinning
1   305800        06 Winning van aardolie en aardgas
2   306300  08 Delfstoffenwinning (geen olie en gas)
3   307500                               C Industrie
4   307610   10-12 Voedings-, genotmiddelenindustrie
5   307600              10 Voedingsmiddelenindustrie
6   307700   101 Slachterijen en vleeswarenindustrie
7   307800         1011 Slachterijen (geen pluimvee)
8   307900                 1012 Pluimveeslachterijen
9   308000           1013 Vleesverwerkende industrie
10  308100              102 Visverwerkende industrie
11  308300  103 Groente-, fruitverwerkende industrie
12  308400          1031 Aardappelproductenindustrie
13  308500     1032 Fruit- en groentesappenindustrie
14  308600  1039 Groente-,fruitverwerkende industrie
15  308700  104 Spijsoliën- en -vettenindustrie e.d.
16  308800      1041 Spijsoliën- en -vettenindustrie
17  309000                       105 Zuivelindustrie
18  309100           1051 Zuivelindustrie (geen ijs)
19  309300                         106 Meelindustrie
20  309400         1061 Meelindustrie (geen zetmeel)
21  309600          107 Brood- en deegwarenindustrie
22  309700           1071 Brood- en banketbakkerijen
23  310000     108 Overige voedingsmiddelenindustrie
24  310100                      1081 Suikerindustrie
25  310200     1082 Cacao- en chocoladewerkindustrie
26  311000                   109 Diervoederindustrie
27  311300                       11 Drankenindustrie
28  311600          1102 Wijnindustrie (uit druiven)
29  312100                   1107 Frisdrankindustrie
..     ...                                       ...
37  317105      17-18 Papier- en grafische industrie
38  317100                        17 Papierindustrie
39  318600                    18 Grafische industrie
40  320005            19-22 Raffinaderijen en chemie
41  320000                     19 Aardolie-industrie
42  320705  20-21 Chemie en farmaceutische industrie
43  320700                    20 Chemische industrie
44  323200               21 Farmaceutische industrie
45  323700   22 Rubber- en kunststofproductindustrie
46  324600                23 Bouwmaterialenindustrie
47  328110                      24-30, 33 Metalektro
48  800002         24-28 Metalektro (geen transport)
49  328105  24-25 Basismetaal, metaalprod.-industrie
50  328100                   24 Basismetaalindustrie
51  330300               25 Metaalproductenindustrie
52  332905  26-28 Elektrotechn. en machine-industrie
53  332910  26-27 Elektrische en elektron. Industrie
54  332900            26 Elektrotechnische industrie
55  334800         27 Elektrische apparatenindustrie
56  336500                      28 Machine-industrie
57  339205          29-30 Transportmiddelenindustrie
58  339200         29 Auto- en aanhangwagenindustrie
59  340200     30 Overige transportmiddelenindustrie
60  341600                        31 Meubelindustrie
61  342400                      32 Overige industrie
62  344400  33 Reparatie en installatie van machines
63  346600                      D Energievoorziening
64  346700                       35 Energiebedrijven
65  348000           E Waterbedrijven en afvalbeheer
66  348100                  36 Waterleidingbedrijven

[67 rows x 2 columns]

### 1.8 Perioden

In [41]:
dfPerioden = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/Perioden")
dfPeriodenlist = dfPerioden["value"].tolist()
dfPeriod = pd.DataFrame(dfPeriodenlist)