In [3]:
import pandas as pd
import json

# 1. Data exploration
deep dive into the world of pandas

## 1.1 UntypedDataSet

In [4]:
# initialiseer dataframe.
dfUntypedDataSet = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/UntypedDataSet?$top=1")

In [5]:
# Loop tot alle data points in dataframe zitten met limiet van 10000 per keer.
top = 9668
skip = 1
while skip < 96681:
    big = dfUntypedDataSet.append(pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/UntypedDataSet?$top=" + str(top) + "&$skip=" + str(skip)))
    skip = skip + 9668
    dfUntypedDataSet = big

Nu hebben we de alle UntypedDataSet in een df, hiervan willen we alleen de values.

In [6]:
# lijst maken van values in df.
DatasetUntypesList = dfUntypedDataSet["value"].tolist()

In [9]:
# dataframe maken van lijst met beoogde values.
newDF = pd.DataFrame(DatasetUntypesList)

In [8]:
newDF

,Afzet,BedrijfstakkenBranchesSBI2008,ID,OntwikkelingTOV1JaarEerder_2,OntwikkelingTOV1MaandEerder_3,Perioden,ProducentenprijsindexPPI_1,Wegingcoefficient_4
0,A6,305700,0,,,1981MM01,53.8,-
1,A6,305700,1,,0.6,1981MM02,54.1,-
2,A6,305700,2,,0.4,1981MM03,54.3,-
3,A6,305700,3,,0.0,1981MM04,54.3,-
4,A6,305700,4,,0.4,1981MM05,54.5,-
5,A6,305700,5,,1.0,1981MM06,55.0,-
6,A6,305700,6,,1.0,1981MM07,55.6,-
7,A6,305700,7,,-0.1,1981MM08,55.5,-
8,A6,305700,8,,-0.2,1981MM09,55.4,-
9,A6,305700,9,,-0.1,1981MM10,55.4,-
10,A6,305700,10,,0.0,1981MM11,55.4,-
11,A6,305700,11,,0.0,1981MM12,55.4,-
12,A6,305700,12,,,1981JJ00,54.9,-
13,A6,305700,13,7.6,4.5,1982MM01,57.9,-
14,A6,305700,14,7.8,0.8,1982MM02,58.3,-
15,A6,305700,15,8.1,0.7,1982MM03,58.7,-
16,A6,305700,16,9.4,1.2,1982MM04,59.4,-
17,A6,305700,17,9.4,0.3,1982MM05,59.6,-
18,A6,305700,18,8.0,-0.3,1982MM06,59.4,-
19,A6,305700,19,6.5,-0.3,1982MM07,59.2,-
20,A6,305700,20,6.2,-0.4,1982MM08,58.9,-
21,A6,305700,21,5.7,-0.6,1982MM09,58.6,-
22,A6,305700,22,5.7,0.0,1982MM10,58.5,-
23,A6,305700,23,6.6,0.8,1982MM11,59.0,-
24,A6,305700,24,6.7,0.2,1982MM12,59.1,-
25,A6,305700,25,7.3,,1982JJ00,58.9,-
26,A6,305700,26,2.5,0.3,1983MM01,59.3,-
27,A6,305700,27,1.7,-0.1,1983MM02,59.3,-
28,A6,305700,28,0.9,0.0,1983MM03,59.2,-
29,A6,305700,29,-0.3,0.0,1983MM04,59.2,-
...,...,...,...,...,...,...,...,...
96651,A5,348100,96651,,,2015MM10,,-
96652,A5,348100,96652,,,2015MM11,,-
96653,A5,348100,96653,,,2015MM12,,-
96654,A5,348100,96654,,,2015JJ00,,-
96655,A5,348100,96655,,,2016MM01,,-
96656,A5,348100,96656,,,2016MM02,,-
96657,A5,348100,96657,,,2016MM03,,-
96658,A5,348100,96658,,,2016MM04,,-
96659,A5,348100,96659,,,2016MM05,,-
96660,A5,348100,96660,,,2016MM06,,-
96661,A5,348100,96661,,,2016MM07,,-
96662,A5,348100,96662,,,2016MM08,,-
96663,A5,348100,96663,,,2016MM09,,-
96664,A5,348100,96664,,,2016MM10,,-
96665,A5,348100,96665,,,2016MM11,,-
96666,A5,348100,96666,,,2016MM12,,-
96667,A5,348100,96667,,,2016JJ00,,-
96668,A5,348100,96668,,,2017MM01,,-
96669,A5,348100,96669,,,2017MM02,,-
96670,A5,348100,96670,,,2017MM03,,-
96671,A5,348100,96671,,,2017MM04,,-
96672,A5,348100,96672,,,2017MM05,,-
96673,A5,348100,96673,,,2017MM06,,-
96674,A5,348100,96674,,,2017MM07,,-
96675,A5,348100,96675,,,2017MM08,,-
96676,A5,348100,96676,,,2017MM09,,-
96677,A5,348100,96677,,,2017MM10,,-
96678,A5,348100,96678,,,2017MM11,,-
96679,A5,348100,96679,,,2017MM12,,-
96680,A5,348100,96680,,,2017JJ00,,-

## 1.2 Typed DataSet

In [10]:
dftypedDataSet = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/TypedDataSet?$top=1")

In [11]:
top = 9668
skip = 1
url = "http://opendata.cbs.nl/ODataApi/OData/81975NED/TypedDataSet"
while skip < 96681:
    big = dftypedDataSet.append(pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/TypedDataSet?$top=" + str(top) + "&$skip=" + str(skip)))
    skip = skip + 9668
    dftypedDataSet = big

In [12]:
# lijst maken van values in df.
DatasetTypedList = dftypedDataSet["value"].tolist()

In [13]:
# dataframe maken van lijst met beoogde values.
newDF2 = pd.DataFrame(DatasetTypedList)

In [14]:
newDF2

,Afzet,BedrijfstakkenBranchesSBI2008,ID,OntwikkelingTOV1JaarEerder_2,OntwikkelingTOV1MaandEerder_3,Perioden,ProducentenprijsindexPPI_1,Wegingcoefficient_4
0,A6,305700,0,NaN,NaN,1981MM01,53.8,0.0
1,A6,305700,1,NaN,0.6,1981MM02,54.1,0.0
2,A6,305700,2,NaN,0.4,1981MM03,54.3,0.0
3,A6,305700,3,NaN,0.0,1981MM04,54.3,0.0
4,A6,305700,4,NaN,0.4,1981MM05,54.5,0.0
5,A6,305700,5,NaN,1.0,1981MM06,55.0,0.0
6,A6,305700,6,NaN,1.0,1981MM07,55.6,0.0
7,A6,305700,7,NaN,-0.1,1981MM08,55.5,0.0
8,A6,305700,8,NaN,-0.2,1981MM09,55.4,0.0
9,A6,305700,9,NaN,-0.1,1981MM10,55.4,0.0
10,A6,305700,10,NaN,0.0,1981MM11,55.4,0.0
11,A6,305700,11,NaN,0.0,1981MM12,55.4,0.0
12,A6,305700,12,NaN,NaN,1981JJ00,54.9,0.0
13,A6,305700,13,7.6,4.5,1982MM01,57.9,0.0
14,A6,305700,14,7.8,0.8,1982MM02,58.3,0.0
15,A6,305700,15,8.1,0.7,1982MM03,58.7,0.0
16,A6,305700,16,9.4,1.2,1982MM04,59.4,0.0
17,A6,305700,17,9.4,0.3,1982MM05,59.6,0.0
18,A6,305700,18,8.0,-0.3,1982MM06,59.4,0.0
19,A6,305700,19,6.5,-0.3,1982MM07,59.2,0.0
20,A6,305700,20,6.2,-0.4,1982MM08,58.9,0.0
21,A6,305700,21,5.7,-0.6,1982MM09,58.6,0.0
22,A6,305700,22,5.7,0.0,1982MM10,58.5,0.0
23,A6,305700,23,6.6,0.8,1982MM11,59.0,0.0
24,A6,305700,24,6.7,0.2,1982MM12,59.1,0.0
25,A6,305700,25,7.3,NaN,1982JJ00,58.9,0.0
26,A6,305700,26,2.5,0.3,1983MM01,59.3,0.0
27,A6,305700,27,1.7,-0.1,1983MM02,59.3,0.0
28,A6,305700,28,0.9,0.0,1983MM03,59.2,0.0
29,A6,305700,29,-0.3,0.0,1983MM04,59.2,0.0
...,...,...,...,...,...,...,...,...
96651,A5,348100,96651,NaN,NaN,2015MM10,NaN,0.0
96652,A5,348100,96652,NaN,NaN,2015MM11,NaN,0.0
96653,A5,348100,96653,NaN,NaN,2015MM12,NaN,0.0
96654,A5,348100,96654,NaN,NaN,2015JJ00,NaN,0.0
96655,A5,348100,96655,NaN,NaN,2016MM01,NaN,0.0
96656,A5,348100,96656,NaN,NaN,2016MM02,NaN,0.0
96657,A5,348100,96657,NaN,NaN,2016MM03,NaN,0.0
96658,A5,348100,96658,NaN,NaN,2016MM04,NaN,0.0
96659,A5,348100,96659,NaN,NaN,2016MM05,NaN,0.0
96660,A5,348100,96660,NaN,NaN,2016MM06,NaN,0.0
96661,A5,348100,96661,NaN,NaN,2016MM07,NaN,0.0
96662,A5,348100,96662,NaN,NaN,2016MM08,NaN,0.0
96663,A5,348100,96663,NaN,NaN,2016MM09,NaN,0.0
96664,A5,348100,96664,NaN,NaN,2016MM10,NaN,0.0
96665,A5,348100,96665,NaN,NaN,2016MM11,NaN,0.0
96666,A5,348100,96666,NaN,NaN,2016MM12,NaN,0.0
96667,A5,348100,96667,NaN,NaN,2016JJ00,NaN,0.0
96668,A5,348100,96668,NaN,NaN,2017MM01,NaN,0.0
96669,A5,348100,96669,NaN,NaN,2017MM02,NaN,0.0
96670,A5,348100,96670,NaN,NaN,2017MM03,NaN,0.0
96671,A5,348100,96671,NaN,NaN,2017MM04,NaN,0.0
96672,A5,348100,96672,NaN,NaN,2017MM05,NaN,0.0
96673,A5,348100,96673,NaN,NaN,2017MM06,NaN,0.0
96674,A5,348100,96674,NaN,NaN,2017MM07,NaN,0.0
96675,A5,348100,96675,NaN,NaN,2017MM08,NaN,0.0
96676,A5,348100,96676,NaN,NaN,2017MM09,NaN,0.0
96677,A5,348100,96677,NaN,NaN,2017MM10,NaN,0.0
96678,A5,348100,96678,NaN,NaN,2017MM11,NaN,0.0
96679,A5,348100,96679,NaN,NaN,2017MM12,NaN,0.0
96680,A5,348100,96680,NaN,NaN,2017JJ00,NaN,0.0

### 1.3TableInfos

In [15]:
dfTableInfos = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/TableInfos")

In [22]:
dfTableInfos["value"]

0    {u'MetaDataModified': u'2018-03-19T02:00:00', ...
Name: value, dtype: object

### 1.4 DataProperties

In [29]:
dfDataProperties = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/DataProperties")
dfDataPropertiesList = dfDataProperties["value"].tolist()
newDF3 = pd.DataFrame(dfDataPropertiesList)
newDF3

,Datatype,Decimals,Default,Description,ID,Key,ParentID,Position,ReleasePolicy,Title,Type,Unit,odata.type
0,NaN,NaN,NaN,,0,Afzet,None,0,NaN,Afzet,Dimension,NaN,Cbs.OData.Dimension
1,NaN,NaN,NaN,,1,BedrijfstakkenBranchesSBI2008,None,1,NaN,Bedrijfstakken/branches SBI 2008,Dimension,NaN,Cbs.OData.Dimension
2,NaN,NaN,NaN,,2,Perioden,None,2,True,Perioden,TimeDimension,NaN,Cbs.OData.TimeDimension
3,Double,1.0,Impossible,De producentenprijsindex (PPI) basis 2010=100 ...,3,ProducentenprijsindexPPI_1,None,3,NaN,Producentenprijsindex (PPI),Topic,2010 = 100,Cbs.OData.Topic
4,Double,1.0,Impossible,De procentuele ontwikkeling van een bepaalde p...,4,OntwikkelingTOV1JaarEerder_2,None,4,NaN,Ontwikkeling t.o.v. 1 jaar eerder,Topic,%,Cbs.OData.Topic
5,Double,1.0,Impossible,De procentuele ontwikkeling van een bepaalde p...,5,OntwikkelingTOV1MaandEerder_3,None,5,NaN,Ontwikkeling t.o.v. 1 maand eerder,Topic,%,Cbs.OData.Topic
6,Double,0.0,Zero,Wegingscoëfficiënten zijn verhoudingsgetallen ...,6,Wegingcoefficient_4,None,6,NaN,Wegingcoëfficiënt,Topic,,Cbs.OData.Topic

### 1.5 CategoryGroups

In [30]:
dfCategoryGroups = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/CategoryGroups")
dfCategoryGroupsList = dfCategoryGroups["value"].tolist()
newDF4 = pd.DataFrame(dfCategoryGroupsList)
newDF4

,Description,DimensionKey,ID,ParentID,Title
0,,BedrijfstakkenBranchesSBI2008,0,NaN,Bedrijfstakken 1e digit (SBI 2008)
1,,BedrijfstakkenBranchesSBI2008,1,0.0,Bedrijfstakken 1e digit
2,,BedrijfstakkenBranchesSBI2008,2,NaN,Bedrijfstakken 2e digit (SBI 2008)
3,,BedrijfstakkenBranchesSBI2008,3,2.0,Bedrijfstakken 2e digit
4,,BedrijfstakkenBranchesSBI2008,4,2.0,Samentellingen bedrijfstakken 2e digit
5,,BedrijfstakkenBranchesSBI2008,5,NaN,Bedrijfstakken 3e digit (SBI 2008)
6,,BedrijfstakkenBranchesSBI2008,6,5.0,Bedrijfstakken 3e digit
7,,BedrijfstakkenBranchesSBI2008,7,NaN,Bedrijfstakken 4e digit (SBI 2008)
8,,BedrijfstakkenBranchesSBI2008,8,7.0,Bedrijfstakken 4e digit
9,,BedrijfstakkenBranchesSBI2008,9,NaN,"Bedrijfstakken 2e digit, naar 1e digit"
10,Deze sectie omvat:\r\n- de winning van in de n...,BedrijfstakkenBranchesSBI2008,10,9.0,B Delfstoffenwinning
11,"Deze sectie omvat:\r\n- de mechanische, fysisc...",BedrijfstakkenBranchesSBI2008,11,9.0,C Industrie
12,Deze sectie omvat:\r\nProductie en distributie...,BedrijfstakkenBranchesSBI2008,12,9.0,D Energievoorziening
13,Deze sectie omvat:\r\n- winning en distributie...,BedrijfstakkenBranchesSBI2008,13,9.0,E Waterbedrijven en afvalbeheer
14,,BedrijfstakkenBranchesSBI2008,14,9.0,Samentellingen Bedrijfstakken 2e digit
15,,BedrijfstakkenBranchesSBI2008,15,NaN,"Bedrijfstakken 3e digit, naar 2e digit"
16,Vervaardiging van voedingsmiddelen,BedrijfstakkenBranchesSBI2008,16,15.0,10 Voedingsmiddelenindustrie
17,,BedrijfstakkenBranchesSBI2008,17,NaN,"Bedrijfstakken 4e digit, naar 2e digit"
18,Vervaardiging van voedingsmiddelen,BedrijfstakkenBranchesSBI2008,18,17.0,10 Voedingsmiddelenindustrie
19,Vervaardiging van dranken,BedrijfstakkenBranchesSBI2008,19,17.0,11 Drankenindustrie

### 1.6 Afzet

In [31]:
dfAfzet = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/Afzet")
dfAfzetList = dfAfzet["value"].tolist()
newDF5 = pd.DataFrame(dfAfzetList)
newDF5

,CategoryGroupID,Description,Key,Title
0,None,Afzet van in Nederland geproduceerde goederen ...,A6,Totaal
1,None,Binnenlandse afzet van in Nederland geproducee...,A4,Binnenlandse afzet
2,None,Buitenlandse afzet van in Nederland geproducee...,A5,Buitenlandse afzet

### 1.7 BedrijfstakkenBranchesSBI2008

In [32]:
dfBedrijfstakkenBranchesSBI2008 = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/BedrijfstakkenBranchesSBI2008")
dfBedrijfstakkenBranchesSBI2008List = dfBedrijfstakkenBranchesSBI2008["value"].tolist()
newDF6 = pd.DataFrame(dfBedrijfstakkenBranchesSBI2008List)
newDF6

,CategoryGroupID,Description,Key,Title
0,1,Winning van delfstoffen\r\nDeze sectie omvat:\...,305700,B Delfstoffenwinning
1,3,Winning van aardolie en aardgas,305800,06 Winning van aardolie en aardgas
2,3,Winning van delfstoffen (geen olie en gas)\r\n...,306300,08 Delfstoffenwinning (geen olie en gas)
3,1,Industrie\r\nDeze sectie omvat:\r\n- de mechan...,307500,C Industrie
4,4,"Vervaardiging van voedingsmiddelen, dranken en...",307610,"10-12 Voedings-, genotmiddelenindustrie"
5,3,Vervaardiging van voedingsmiddelen,307600,10 Voedingsmiddelenindustrie
6,6,Slachterijen en vleesverwerking\r\nDeze groep ...,307700,101 Slachterijen en vleeswarenindustrie
7,8,Slachterijen (geen pluimvee)\r\nDeze klasse om...,307800,1011 Slachterijen (geen pluimvee)
8,8,Pluimveeslachterijen\r\nDeze klasse omvat:\r\n...,307900,1012 Pluimveeslachterijen
9,8,Vleesverwerking (niet tot maaltijden)\r\nDeze ...,308000,1013 Vleesverwerkende industrie
10,6,Visverwerking\r\nDeze groep omvat:\r\n- verwer...,308100,102 Visverwerkende industrie
11,6,"Verwerking van aardappels, groente en fruit\r\...",308300,"103 Groente-, fruitverwerkende industrie"
12,8,Vervaardiging van aardappelproducten\r\nDeze k...,308400,1031 Aardappelproductenindustrie
13,8,Vervaardiging van fruit- en groentesap\r\nDeze...,308500,1032 Fruit- en groentesappenindustrie
14,8,Verwerking van groente en fruit (niet tot sap ...,308600,"1039 Groente-,fruitverwerkende industrie"
15,6,Vervaardiging van plantaardige en dierlijke ol...,308700,104 Spijsoliën- en -vettenindustrie e.d.
16,8,Vervaardiging van plantaardige en dierlijke ol...,308800,1041 Spijsoliën- en -vettenindustrie
17,6,Vervaardiging van zuivelproducten\r\nDeze groe...,309000,105 Zuivelindustrie
18,8,Vervaardiging van zuivelproducten (geen consum...,309100,1051 Zuivelindustrie (geen ijs)
19,6,Vervaardiging van meel\r\nDeze groep omvat:\r\...,309300,106 Meelindustrie
20,8,Vervaardiging van meel (geen zetmeel)\r\nDeze ...,309400,1061 Meelindustrie (geen zetmeel)
21,6,"Vervaardiging van brood, banketbakkerswerk en ...",309600,107 Brood- en deegwarenindustrie
22,8,Vervaardiging van brood en vers banketbakkersw...,309700,1071 Brood- en banketbakkerijen
23,6,Vervaardiging van overige voedingsmiddelen\r\n...,310000,108 Overige voedingsmiddelenindustrie
24,8,Vervaardiging van suiker\r\nDeze klasse omvat:...,310100,1081 Suikerindustrie
25,8,Verwerking van cacao en vervaardiging van choc...,310200,1082 Cacao- en chocoladewerkindustrie
26,6,Vervaardiging van diervoeders\r\nDeze klasse o...,311000,109 Diervoederindustrie
27,3,Vervaardiging van dranken,311300,11 Drankenindustrie
28,8,Vervaardiging van wijn uit druiven\r\nDeze kla...,311600,1102 Wijnindustrie (uit druiven)
29,8,Vervaardiging van frisdranken; productie van m...,312100,1107 Frisdrankindustrie
...,...,...,...,...
37,4,"Vervaardiging van papier, karton en papier- en...",317105,17-18 Papier- en grafische industrie
38,3,"Vervaardiging van papier, karton en papier- en...",317100,17 Papierindustrie
39,3,"Drukkerijen, reproductie van opgenomen media",318600,18 Grafische industrie
40,4,"Raffinaderijen, chemie, vervaardiging van farm...",320005,19-22 Raffinaderijen en chemie
41,3,Vervaardiging van cokesovenproducten en aardol...,320000,19 Aardolie-industrie
42,4,Vervaardiging van chemische en farmaceutische ...,320705,20-21 Chemie en farmaceutische industrie
43,3,Vervaardiging van chemische producten,320700,20 Chemische industrie
44,3,Vervaardiging van farmaceutische grondstoffen ...,323200,21 Farmaceutische industrie
45,3,Vervaardiging van producten van rubber en kuns...,323700,22 Rubber- en kunststofproductindustrie
46,3,Vervaardiging van overige niet-metaalhoudende ...,324600,23 Bouwmaterialenindustrie
47,4,Metalektro\r\nDeze categorie is een samentelli...,328110,"24-30, 33 Metalektro"
48,4,Metalektro (geen transport) ...,800002,24-28 Metalektro (geen transport)
49,4,Vervaardiging van metalen in primaire vorm en ...,328105,"24-25 Basismetaal, metaalprod.-industrie"
50,3,Vervaardiging van metalen in primaire vorm,328100,24 Basismetaalindustrie
51,3,Vervaardiging van producten van metaal (geen m...,330300,25 Metaalproductenindustrie
52,4,Elektrotechnische en machine-industrie\r\nDeze...,332905,26-28 Elektrotechn. en machine-industrie
53,4,"Vervaardiging van computers en elektronische, ...",332910,26-27 Elektrische en elektron. Industrie
54,3,Vervaardiging van computers en van elektronisc...,332900,26 Elektrotechnische industrie
55,3,Vervaardiging van elektrische apparatuur,334800,27 Elektrische apparatenindustrie
56,3,Vervaardiging van overige machines en apparaten,336500,28 Machine-industrie
57,4,Vervaardiging van transportmiddelen\r\nDeze ca...,339205,29-30 Transportmiddelenindustrie
58,3,"Vervaardiging van auto's, aanhangwagens en opl...",339200,29 Auto- en aanhangwagenindustrie
59,3,Vervaardiging van overige transportmiddelen,340200,30 Overige transportmiddelenindustrie
60,3,Vervaardiging van meubels\r\nDeze afdeling omv...,341600,31 Meubelindustrie
61,3,Vervaardiging van overige goederen,342400,32 Overige industrie
62,3,Reparatie en installatie van machines en appar...,344400,33 Reparatie en installatie van machines
63,1,Productie en distributie van en handel in elek...,346600,D Energievoorziening
64,3,Productie en distributie van en handel in elek...,346700,35 Energiebedrijven
65,1,Winning en distributie van water; afval- en af...,348000,E Waterbedrijven en afvalbeheer
66,3,Winning en distributie van water\r\nDeze afdel...,348100,36 Waterleidingbedrijven

### 1.8 Perioden

In [33]:
dfPerioden = pd.read_json("http://opendata.cbs.nl/ODataApi/OData/81975NED/Perioden")
dfPeriodenList = dfPerioden["value"].tolist()
newDF7 = pd.DataFrame(dfPeriodenList)
newDF7

    Description       Key      Status           Title
0                1981MM01  Definitief    1981 januari
1                1981MM02  Definitief   1981 februari
2                1981MM03  Definitief      1981 maart
3                1981MM04  Definitief      1981 april
4                1981MM05  Definitief        1981 mei
5                1981MM06  Definitief       1981 juni
6                1981MM07  Definitief       1981 juli
7                1981MM08  Definitief   1981 augustus
8                1981MM09  Definitief  1981 september
9                1981MM10  Definitief    1981 oktober
10               1981MM11  Definitief   1981 november
11               1981MM12  Definitief   1981 december
12               1981JJ00  Definitief            1981
13               1982MM01  Definitief    1982 januari
14               1982MM02  Definitief   1982 februari
15               1982MM03  Definitief      1982 maart
16               1982MM04  Definitief      1982 april
17               1982MM05  Definitief        1982 mei
18               1982MM06  Definitief       1982 juni
19               1982MM07  Definitief       1982 juli
20               1982MM08  Definitief   1982 augustus
21               1982MM09  Definitief  1982 september
22               1982MM10  Definitief    1982 oktober
23               1982MM11  Definitief   1982 november
24               1982MM12  Definitief   1982 december
25               1982JJ00  Definitief            1982
26               1983MM01  Definitief    1983 januari
27               1983MM02  Definitief   1983 februari
28               1983MM03  Definitief      1983 maart
29               1983MM04  Definitief      1983 april
..          ...       ...         ...             ...
451              2015MM10  Definitief    2015 oktober
452              2015MM11  Definitief   2015 november
453              2015MM12  Definitief   2015 december
454              2015JJ00  Definitief            2015
455              2016MM01  Definitief    2016 januari
456              2016MM02  Definitief   2016 februari
457              2016MM03  Definitief      2016 maart
458              2016MM04  Definitief      2016 april
459              2016MM05  Definitief        2016 mei
460              2016MM06  Definitief       2016 juni
461              2016MM07  Definitief       2016 juli
462              2016MM08  Definitief   2016 augustus
463              2016MM09  Definitief  2016 september
464              2016MM10  Definitief    2016 oktober
465              2016MM11  Definitief   2016 november
466              2016MM12  Definitief   2016 december
467              2016JJ00  Definitief            2016
468              2017MM01  Definitief    2017 januari
469              2017MM02  Definitief   2017 februari
470              2017MM03  Definitief      2017 maart
471              2017MM04  Definitief      2017 april
472              2017MM05  Definitief        2017 mei
473              2017MM06  Definitief       2017 juni
474              2017MM07  Definitief       2017 juli
475              2017MM08   Voorlopig   2017 augustus
476              2017MM09   Voorlopig  2017 september
477              2017MM10   Voorlopig    2017 oktober
478              2017MM11   Voorlopig   2017 november
479              2017MM12   Voorlopig   2017 december
480              2017JJ00   Voorlopig            2017

[481 rows x 4 columns]